"""table coverage_journeys

Revision ID: 1cc79244cdf
Revises: None
Create Date: 2017-03-02 11:11:06.697861

"""

# revision identifiers, used by Alembic.
revision = '1cc79244cdf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_journeys2',
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('region_id', sa.Text(), nullable=False),
    sa.Column('is_internal_call', sa.Integer(), nullable=False),
    sa.Column('nb', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('request_date', 'region_id', 'is_internal_call'),
    sa.UniqueConstraint('region_id', 'request_date', 'is_internal_call', name='coverage_journeys_pkey2'),
    schema='stat_compiled'
    )
    op.create_table('coverage_journeys_requests_params2',
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('region_id', sa.Text(), nullable=False),
    sa.Column('is_internal_call', sa.Integer(), nullable=False),
    sa.Column('nb_wheelchair', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('request_date', 'region_id', 'is_internal_call'),
    sa.UniqueConstraint('region_id', 'request_date', 'is_internal_call', name='coverage_journeys_requests_params_pkey2'),
    schema='stat_compiled'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    sa.Column('version', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    op.drop_table('coverage_journeys_requests_params2', schema='stat_compiled')
    op.drop_table('coverage_journeys2', schema='stat_compiled')
    ### end Alembic commands ###