FROM gettyimages/spark:2.1.0-hadoop-2.7

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -yq install \
        libpq-dev \
        python-pip \
        python-dev \
        && \
    rm -rf /var/lib/apt/lists/*

ADD requirements-test.txt /tmp/
RUN pip2 install -r /tmp/requirements-test.txt
RUN mkdir /srv/spark-stat-analyzer
WORKDIR /srv/spark-stat-analyzer

CMD ["python", "-m", "pytest"]